name: Pong Game CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-report
          path: coverage/
        
  create-issue:
    permissions:
      issues: write
    needs: test
    if: ${{ failure() && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create issue on test failure
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'CI Tests Failed',
              body: `Tests failed on commit ${context.sha}. [View workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
              labels: ['bug', 'ci-failure']
            })
